backend:
  name: git-gateway
  branch: master

media_folder: "site/static/assets/uploads"
public_folder: "assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "site/content/_index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero", name: "hero", widget: "object", fields: [
              {label: "Image", name: "image", widget: "image"}
            ]}
          - {label: "What Is the MHP?", name: "whatIs", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
            ]}
          - {label: "Who's Involved?", name: "whosInvolved", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Sub-Heading", name: "subHeading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
            ]}
          - {label: "Get Involved", name: "getInvolved", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"},
              {label: "Image", name: "image", widget: "image"}
            ]}
          - {label: "How Does it Work?", name: "howDoesItWork", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"},
              {label: "Image", name: "image", widget: "image"}
            ]}
          - {label: "Charter", name: "charter", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
            ]}
          - {label: "What Else is Happening?", name: "whatElse", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
            ]}
      - file: "site/content/contact-us/_index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Template", name: "layout", widget: "hidden", default: "single"}
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Image", name: "image", widget: "image", required: false},
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Sub-Heading", name: "subHeading", widget: "string", required: false},
              {label: "Body", name: "body", widget: "markdown"}
            ]}
      - file: "site/content/homelessness-strategy/_index.md"
        label: "Homelessness Strategy"
        name: "homelessness-strategy"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero", name: "hero", widget: "object", fields: [
              {label: "Image", name: "image", widget: "image"}
            ]}
          - {label: "About", name: "about", widget: "object", fields: [
            {label: "Heading", name: "heading", widget: "string" },
            {label: "Body", name: "body", widget: "markdown" },
          ]}
          - {label: "Action Plans", name: "actionPlans", widget: "object", fields: [
            {label: "Heading", name: "heading", widget: "string" },
            {label: "Body", name: "body", widget: "markdown" },
          ]}
          - {label: "Strategy Call To Action", name: "strategyCta", widget: "object", fields: [
            {label: "Title", name: "title", widget: "string"},
            {label: "Url", name: "url", widget: "string"}
          ]}
